### ISSUE TITLE
rem始终对应100px

### ISSUE THREAD

**Issue by MisterDeng** [kujian/simple-flexible#1]
我是基于1280的宽度开发的  (1280, 750);
我设置了一个宽度12rem  生成的1200pxdiv
如果窗口变成1920  div宽度还是生成的1200px
这是不是错误的？ 还是我哪里设置的有问题呢？

**Comment by MisterDeng** [comment]
可以了 应该是浏览器的问题

**Comment by kujian** [comment]
后面这个750是设置最大宽度值，如果网页超出750，则以750为最大宽度哦。如果你的最大宽度值是1280.那么你后面这个值也要设置为1280.
